name: Publish release artifacts maven snapshot repo
on:
  release:
    types:
      - published

jobs:
  publish_release_to_maven_central:
    name: Publish release artifacts to Maven repos
    uses: ./.github/workflows/publish-to-maven.yml
    secrets: inherit
    with:
      is-release: true
      version-suffix: '-limited-preview'
      slack-notify: true
